name: "Install C++ Dependencies"
description: "Install C++ dependencies for build and test jobs"
inputs:
  os:
    description: "Operating system"
    required: true
    type: string
  deps_prefix:
    description: "Install prefix for built deps (cached)"
    required: false
    default: "${{ github.workspace }}/.deps"

runs:
  using: "composite"
  steps:
    - name: Show runner info
      shell: bash
      run: |
        echo "Running on OS: ${{ runner.os }}"
        echo "Runner name: ${{ runner.name }}"
    - name: Install CMake and ninja, cross-platform
      if: runner.os != 'MacOS'  # macOS uses brew for this, as it's bundled with Fortran
      uses: lukka/get-cmake@latest
      # Default caching options are suitable for GH hosted runners
    - name: Linux Dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ gfortran
    - name: macOS Dependencies
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew update
        brew install gcc
        # We need to add Fortran compiler to the environment:
        which gfortran
    - name: Windows dependencies (winget)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        winget --version
        winget source update
        winget install -e --id LLVM.LLVM `
          --accept-package-agreements --accept-source-agreements --disable-interactivity
        # Make LLVM immediately available to later steps
        echo 'C:\Program Files\LLVM\bin' | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - name: Windows gfortran (MSYS2)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        winget install -e --id MSYS2.MSYS2 `
          --accept-package-agreements --accept-source-agreements --disable-interactivity
        & 'C:\msys64\usr\bin\bash.exe' -lc "pacman -Sy --noconfirm --needed mingw-w64-x86_64-gcc-fortran"
        echo 'C:\msys64\mingw64\bin' | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      # Dependencies are cloned via HTTPs to avoid SSH key issues on GitHub runners
      # Alternatively, we could provide an AUTH token secret to the action
      # They are then built and installed, with caching based on OS and architecture
    - name: Install Catch2
      uses: ./.github/actions/clone-cache-install
      with:
        dependency_name: "catch2"
        dependency_repo: "https://github.com/catchorg/Catch2.git"
        cmake_options: "-DBUILD_TESTING=OFF"

    - name: Install LAPACK
      uses: ./.github/actions/clone-cache-install
      with:
        dependency_name: "lapack"
        dependency_repo: "https://github.com/Reference-LAPACK/lapack.git"
        cmake_options: "-DBUILD_SHARED_LIBS=ON -DLAPACKE=ON"

