name: "Install C++ Dependencies"
description: "Install C++ dependencies for build and test jobs"
inputs:
  os:
    description: "Operating system"
    required: true
    type: string
runs:
  using: "composite"
  defaults:
    run:
      shell: bash -el {0}
  steps:
    - name: Show runner info
      run: |
        echo "Running on OS: ${{ runner.os }}"
        echo "Runner name: ${{ runner.name }}"
    
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        activate-environment: build-env
        channels: conda-forge
        channel-priority: strict
    
    - name: Install dependencies via conda
      run: |
        conda install -y cmake ninja openblas catch2
        
    - name: Verify installations
      run: |
        cmake --version
        ninja --version
        ls $CONDA_PREFIX/include/lapacke.h
        ls $CONDA_PREFIX/lib/cmake/Catch2
