name: "Install C++ Dependencies"
description: "Install C++ dependencies for build and test jobs"
inputs:
  os:
    description: "Operating system"
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Show runner info
      shell: bash -el {0}
      run: |
        echo "Running on OS: ${{ runner.os }}"
        echo "Runner name: ${{ runner.name }}"
    
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        activate-environment: QUGaR
        channels: conda-forge
        channel-priority: strict
    
    - name: Install dependencies via conda
      shell: bash -el {0}
      run: |
        conda install -y cmake ninja liblapacke openblas catch2
        
    - name: Verify installations
      shell: bash -el {0}
      run: |
        cmake --version
        ninja --version
        echo "CONDA_PREFIX: $CONDA_PREFIX"
        echo "CONDA_PREFIX: $CONDA_PREFIX"
    
        # Convert Windows path to Unix path for bash tools
        UNIX_PREFIX=$(cygpath "$CONDA_PREFIX" 2>/dev/null || echo "$CONDA_PREFIX")
        echo "UNIX_PREFIX: $UNIX_PREFIX"
        
        echo "Listing Library directory:"
        ls "$UNIX_PREFIX"/Library/include/ 2>/dev/null || echo "Library/include not found"
        
        echo "Searching for lapacke:"
        find "$UNIX_PREFIX" -name "*lapacke*" 2>/dev/null || echo "No lapacke files found"
