name: "Install Python Dependencies"
description: "Install Python dependencies for build and test jobs"
# The idea is to provide caching mechanism for conda packages to speed up
# the workflows. However, there is currently no way to safely cache conda
# environments on GH runners. Leaving this as a simple action for now, in
# the hope that caching will be possible in the future.
inputs:
  os:
    description: "Operating system"
    required: true
    default: "ubuntu-latest"
  pyvista_version:
    description: "PyVista version to install"
    required: false
    default: "0.44.1"

runs:
  using: "composite"
  steps:
    - name: Show runner info
      shell: bash
      run: |
        echo "Running on OS: ${{ runner.os }}"
        echo "Runner name: ${{ runner.name }}"

    # NOTE:
    # Caching conda packages does not seem to be possible at the moment due to
    # the need to use use-only-tar-bz2 for setup-miniconda, which clashes with
    # the fenicsx packages. Caching is turned off for now.
    # - name: Cache conda packages
    #   uses: actions/cache@v4
    #   with:
    #     path: ~/conda_pkgs_dir
    #     key: ${{ runner.os }}-${{ runner.arch }}-conda-fenicsx

    - name: Install conda for FenicsX
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: QUGaR
        environment-file: environment-dev.yml
        auto-activate-base: false
        # use-only-tar-bz2: true # This is needed for caching to work properly, but clashes with fenicsx packages

    - name: Install Build Requrements
      shell: bash -el {0}
      run: |
        python -m pip install build wheel
